#!/usr/bin/env node

/*
compress - Compress .nexus file into Nexus Client settings .nxs file
Copyright (C) 2018 Gustav W. Bertram

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

var fs = require("fs");

// Print usage
function usage() {
    console.log("Usage: ./compress <file>.nexus");
    process.exitCode = 1;
}

function uglify(data) {
    return data = JSON.stringify(JSON.parse(data));
}

if (process.argv.length < 3) {
    usage();
} else {
    filename = process.argv[2];
    file = fs.readFileSync(filename, 'utf8');

    // Create or replace existing file
    fs.writeFileSync(filename.replace("nexus","nxs"), uglify(file));
}
